version: "2.3"

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:

services:
  elasticsearch:
    image: elasticsearch:2.4
    container_name: elasticsearch1
    command: elasticsearch --cluster.name=docker-cluster --node.name=master --ES_JAVA_OPTS="Xms512m -Xmx512m" --bootstrap.memory_lock=true
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

  elasticsearch2:
    image: elasticsearch:2.4
    container_name: elasticsearch2
    restart: always
    command: elasticsearch --discovery.zen.ping.unicast.hosts=elasticsearch1 --cluster.name=docker-cluster --node.name=slaver --ES_JAVA_OPTS="Xms512m -Xmx512m" --bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    depends_on:
      - elasticsearch
    networks:
      - esnet

  kopf:
    build:
      context: ./
      dockerfile: env_setting/kopf
    container_name: elastinterface
    restart: always
    environment:
      TZ: "Asia/Taipei"
    ports:
      - 9000:9000
    networks:
      - esnet

  api:
    build:
      context: ./
      dockerfile: env_setting/api_server
    container_name: api
    restart: always
    environment:
      TZ: "Asia/Taipei"
    ports:
      - 5000:80
    volumes:
      - ./source_code:/app
    networks:
      - esnet

