version: "3"

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  mysqldata:
    driver: local
  redisdata:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5
    container_name: elasticsearch1
    restart: always
    environment:
      - TZ=Asia/Taipei
      - node.name=es1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=elasticsearch2,elasticsearch3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5
    container_name: elasticsearch2
    restart: always
    environment:
      - TZ=Asia/Taipei
      - node.name=es2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5
    container_name: elasticsearch3
    restart: always
    environment:
      - TZ=Asia/Taipei
      - node.name=es3
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data

  kopf:
    image: lmenezes/cerebro:0.8.1
    container_name: elastinterface
    restart: always
    environment:
      TZ: "Asia/Taipei"
    volumes:
      - ./env_setting/kopf.config:/opt/cerebro/conf/application.conf
    ports:
      - 9000:9000

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      TZ: "Asia/Taipei"
      MYSQL_ROOT_PASSWORD: "please modify this value"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    sysctl:
      net.core.somaxconn: 4096
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - redisdata:/data
      - ./env_setting/redis.config:/usr/local/etc/redis/redis.conf
      
  api:
    build:
      context: ./
      dockerfile: env_setting/api_server
    image: ycyang/api:latest
    container_name: api
    restart: always
    environment:
      TZ: "Asia/Taipei"
    ports:
      - 5000:80
    volumes:
      - ./source_code:/app


